FROM node:23-alpine

WORKDIR /app

# Install git and development dependencies
RUN apk add --no-cache git dos2unix

# Copy package files
COPY package*.json ./
COPY tsconfig.json ./
COPY prisma ./prisma/

# Install all dependencies (including dev dependencies)
RUN npm install

# Generate Prisma client
RUN npx prisma generate

# Expose the application port
EXPOSE 8080
# Expose Prisma Studio port
EXPOSE 5555